export const Supported_Language = [
  {
    identifier: "en",
    name: "English",
  },
  {
    identifier: "hindi",
    name: "Hindi (हिंदी)",
  },
  {
    identifier: "spanish",
    name: "Spanish (Español)",
  },
];

export const Text_Based_On_Language = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What would you like to watch today?",
    home: "Home",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    newToNetflix: "New to Netflix?",
    password: "Password",
    email: "Email Address",
    name: "Full Name",
    alreadyAcc: "Already have an account?",
    welcome: "Welcome,",
    gptSearch: "GPT Search",
    forgotPass: "Forgot Password?",
    forgotPassMessage:
      "We will send you an password reset link on your email to reset your password.",
    emailMe: "Email Me",
    emailPlaceholder: "name@example.com",
    back: "Back",
    playNow: "Play Now",
    moreInfo: "More Info",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upcoming: "Upcoming",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    home: "घर",
    signIn: "दाखिल करें",
    signUp: "साइन अप करें",
    signOut: "साइन आउट",
    newToNetflix: "Netflix पर नए हैं?",
    password: "पासवर्ड",
    email: "मेल पता",
    name: "पूरा नाम",
    alreadyAcc: "क्या आपके पास पहले से एक खाता मौजूद है?",
    welcome: "स्वागत,",
    gptSearch: "जीपीटी खोज",
    forgotPass: "पासवर्ड भूल गए?",
    forgotPassMessage:
      "आपका पासवर्ड रीसेट करने के लिए हम आपको आपके ईमेल पर एक पासवर्ड रीसेट लिंक भेजेंगे।",
    emailMe: "मुझे ईमेल करो",
    emailPlaceholder: "name@example.com",
    back: "पीछे",
    playNow: "अभी चलाएं",
    moreInfo: "और जानकारी",
    nowPlaying: "अभी चल रही है",
    popular: "लोकप्रिय",
    topRated: "टॉप रेटेड",
    upcoming: "आगामी",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    home: "Hogar",
    signIn: "Iniciar sesión",
    signUp: "Inscribirse",
    signOut: "Desconectar",
    newToNetflix: "¿Nuevo en Netflix?",
    password: "Contraseña",
    email: "Dirección de correo electrónico",
    name: "Nombre completo",
    alreadyAcc: "¿Ya tienes una cuenta?",
    welcome: "Bienvenido,",
    gptSearch: "Búsqueda GPT",
    forgotPass: "¿Has olvidado tu contraseña?",
    forgotPassMessage:
      "Le enviaremos un enlace de restablecimiento de contraseña a su correo electrónico para restablecer su contraseña.",
    emailMe: "Envíeme un correo electrónico",
    emailPlaceholder: "nombre@ejemplo.com",
    back: "Atrás",
    playNow: "Reproducir ahora",
    moreInfo: "Más información",
    nowPlaying: "Jugando ahora",
    popular: "Popular",
    topRated: "Los más valorados",
    upcoming: "Próximo",
  },
};
